name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jerryzs/action-dependabot-auto-merge@v2
        with:
          target: minor
          method: rebase
          github-token: ${{ secrets.GITHUB_TOKEN }}
